import java.util.Scanner; 

public class BANK {
    public static void main(String args[]) {
        Scanner s1 = new Scanner(System.in); 

        System.out.print("Enter username: ");
        String username = s1.nextLine(); 
        System.out.println("Username: " + username);

        System.out.print("Enter password: ");
        String password = s1.nextLine(); 
        System.out.println("Password: " + password);

        
    }
}
